pub const Key = enum {
    // 数字
    zero,
    one,
    two,
    three,
    four,
    five,
    six,
    seven,
    eight,
    nine,

    // アルファベット
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    q,
    r,
    s,
    t,
    u,
    v,
    w,
    x,
    y,
    z,

    // 空白・制御文字
    space,
    enter,
    tab,
    escape,
    backspace,
    delete,

    // 矢印キー
    arrow_up,
    arrow_down,
    arrow_left,
    arrow_right,

    // 修飾キー
    shift,
    ctrl,
    alt,
    meta,
    caps_lock,

    // ファンクションキー
    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,

    // 記号キー
    minus,
    equal,
    left_bracket,
    right_bracket,
    backslash,
    semicolon,
    quote,
    grave,
    comma,
    period,
    slash,

    unknown,
};

pub fn mapByteToKey(b: u8) Key {
    switch (b) {
        // 数字
        '0' => return Key.zero,
        '1' => return Key.one,
        '2' => return Key.two,
        '3' => return Key.three,
        '4' => return Key.four,
        '5' => return Key.five,
        '6' => return Key.six,
        '7' => return Key.seven,
        '8' => return Key.eight,
        '9' => return Key.nine,

        // アルファベット
        'a', 'A' => return Key.a,
        'b', 'B' => return Key.b,
        'c', 'C' => return Key.c,
        'd', 'D' => return Key.d,
        'e', 'E' => return Key.e,
        'f', 'F' => return Key.f,
        'g', 'G' => return Key.g,
        'h', 'H' => return Key.h,
        'i', 'I' => return Key.i,
        'j', 'J' => return Key.j,
        'k', 'K' => return Key.k,
        'l', 'L' => return Key.l,
        'm', 'M' => return Key.m,
        'n', 'N' => return Key.n,
        'o', 'O' => return Key.o,
        'p', 'P' => return Key.p,
        'q', 'Q' => return Key.q,
        'r', 'R' => return Key.r,
        's', 'S' => return Key.s,
        't', 'T' => return Key.t,
        'u', 'U' => return Key.u,
        'v', 'V' => return Key.v,
        'w', 'W' => return Key.w,
        'x', 'X' => return Key.x,
        'y', 'Y' => return Key.y,
        'z', 'Z' => return Key.z,

        // 空白・制御文字
        ' ' => return Key.space,
        '\n' => return Key.enter,
        '\t' => return Key.tab,
        0x08 => return Key.backspace,
        0x7F => return Key.delete,

        // 記号
        '-' => return Key.minus,
        '=' => return Key.equal,
        '[' => return Key.left_bracket,
        ']' => return Key.right_bracket,
        '\\' => return Key.backslash,
        ';' => return Key.semicolon,
        '\'' => return Key.quote,
        '`' => return Key.grave,
        ',' => return Key.comma,
        '.' => return Key.period,
        '/' => return Key.slash,

        else => return Key.unknown,
    }
}
